version: '3.1'

services:

  # Use root/root as user/password credentials
  mysql:
    container_name: "skillbox-mysql"
    restart: on-failure
    image: mysql:8.1.0
    command: [
      "--default-authentication-plugin=mysql_native_password"
    ]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: skillbox
      MYSQL_PASSWORD: skillbox
      MYSQL_DATABASE: skillboxdb

  redis:
    container_name: "skillbox-redis"
    image: redis:7.2.3
    restart: on-failure
    ports:
      - '6379:6379'
