version: '3.1'

services:

  # Use root/root as user/password credentials
  mysql:
    container_name: "skillbox-mysql"
    restart: on-failure
    image: mysql:8.1.0
    command: [
      "--default-authentication-plugin=mysql_native_password"
    ]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: skillbox
      MYSQL_PASSWORD: skillbox
      MYSQL_DATABASE: skillboxdb

  mongo:
    image: mongo:7.0.3
    restart: always
    ports:
      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "./example-data/mongo:/tmp/migration_data:ro"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  redis:
    container_name: "skillbox-redis"
    image: redis:7.2.3
    restart: on-failure
    ports:
      - '6379:6379'
